// Generated by CoffeeScript 1.3.3
(function() {
  var persist, raw, savedImages;

  if (raw = localStorage.getItem("savedImages")) {
    savedImages = JSON.parse(raw);
  } else {
    savedImages = {};
  }

  persist = function() {
    return localStorage.setItem("savedImages", JSON.stringify(savedImages));
  };

  chrome.extension.onMessage.addListener(function(payload, sender, cb) {
    switch (payload._action) {
      case "fetchImages":
        chrome.tabs.getSelected(null, function(tab) {
          return chrome.tabs.sendMessage(tab.id, {
            _action: "fetchImages"
          }, function(payload) {
            var err, img, key, keys, pageImages;
            err = payload[0], pageImages = payload[1];
            console.log("hit", pageImages, savedImages);
            keys = Object.keys(savedImages);
            pageImages = _(pageImages).reject(function(img) {
              return _(keys).include(img.src);
            });
            for (key in savedImages) {
              img = savedImages[key];
              pageImages.push(img);
            }
            return cb([err, pageImages]);
          });
        });
        return true;
      case "saveImage":
        savedImages[payload.src] = {
          src: payload.src,
          width: payload.width,
          height: payload.height,
          saved: true
        };
        return persist();
      case "unsaveImage":
        delete savedImages[payload.src];
        return persist();
    }
  });

}).call(this);
