// Generated by CoffeeScript 1.3.3
(function() {
  var absolutizeSrc, fetchImages;

  absolutizeSrc = function(src) {
    var path;
    if (/^\//.test(src)) {
      return window.location.origin + src;
    } else if (/^http/.test(src)) {
      return src;
    } else {
      path = ("" + window.location.pathname).replace(/\/[^\/]+$/, "/");
      return window.location.origin + path + src;
    }
  };

  fetchImages = function() {
    var out;
    out = [];
    $("img").each(function() {
      var $img;
      $img = $(this);
      if ($img.width() > 10 && $img.height() > 10) {
        return out.push({
          src: absolutizeSrc($img.attr("src")),
          width: $img.width(),
          height: $img.height()
        });
      }
    });
    return out;
  };

  chrome.extension.onMessage.addListener(function(payload, sender, cb) {
    if (payload._action === "fetchImages") {
      try {
        return cb([null, fetchImages()]);
      } catch (e) {
        return cb([e]);
      }
    }
  });

}).call(this);
