// Generated by CoffeeScript 1.3.3
(function() {
  var ImageSaver;

  ImageSaver = angular.module("ImageSaver", ["ng"]);

  ImageSaver.controller("Popup", function($scope) {
    return $scope.name = "World";
  });

}).call(this);
